FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    nmap \
    tcpdump \
    libpcap-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY attacker.py .

CMD ["python", "attackerTest.py"]